### ISSUE TITLE
Missing builds for serial + vga

### ISSUE THREAD

**Issue by DuckyPolice** [Memotech-Bill/PicoBB#24]
I have tried tirelessly for hours to build the serial + vga builds but its very difficult. it would be good to include the builds as many people do not have a OTG adapter and can't build the correct uf2. the whole build process is confusing.

**Comment by Memotech-Bill** [comment]
What has an OTG adapter have to do with anything?

Have you downloaded my latest updates (`git pull`)?

What options have you used and what errors do you obtain?

What to you mean by serial? USB is serial (Universal **Serial** Bus). Or do you mean UART (universal asynchronous receiver / transmitter)?

What other options do you want?

* Pico or Pico W?
* Console on USB, UART or both?
* A non-console UART connection for use from BASIC?
* Printer support from BASIC?
* With or without Flash storage?
* With or without SD card?
* With or without sound? Sound as I2S or PWM?
* Which pins to use?

There are too many possible options for me to supply ready-made builds for all of them.
